#include <stdio.h>
#include "../include/account.h"
#include "../include/file_handler.h"
#include "../include/utils.h"
static void printAccount(const Account *a, int complete) { printf("\nAccount Number : %d\nAccount Holder : %s\n", a->accountNumber, a->holderName); if (complete) printf("Mobile Number  : %s\nEmail Address  : %s\n", a->mobileNumber, a->emailAddress); printf("Account Type   : %s\nCurrent Balance: %.2f\n", a->accountType, a->balance); }
void createAccount(void) { Account a, existing; do { a.accountNumber = readInt("\nAccount Number: "); if (a.accountNumber <= 0) puts("Account number must be positive."); } while (a.accountNumber <= 0); if (findAccount(a.accountNumber, &existing)) { puts("An account with this number already exists."); return; } readLine("Account Holder Name: ", a.holderName, sizeof a.holderName); readLine("Mobile Number: ", a.mobileNumber, sizeof a.mobileNumber); readLine("Email Address: ", a.emailAddress, sizeof a.emailAddress); readLine("Account Type (Savings/Current): ", a.accountType, sizeof a.accountType); a.balance = readNonnegativeAmount("Initial Deposit: "); puts(appendAccount(&a) ? "Account created successfully." : "File write error."); }
void viewAccountDetails(void) { Account a; if (findAccount(readInt("\nAccount Number: "), &a)) printAccount(&a, 1); else puts("Account not found."); }
void updateAccount(void) { Account a; int n = readInt("\nAccount Number: "); if (!findAccount(n, &a)) { puts("Account not found."); return; } readLine("New Holder Name: ", a.holderName, sizeof a.holderName); readLine("New Mobile Number: ", a.mobileNumber, sizeof a.mobileNumber); readLine("New Email Address: ", a.emailAddress, sizeof a.emailAddress); readLine("New Account Type: ", a.accountType, sizeof a.accountType); puts(replaceAccount(&a) ? "Account updated successfully." : "File write error."); }
void deleteAccount(void) { int n = readInt("\nAccount Number: "); puts(removeAccount(n) ? "Account deleted successfully." : "Account not found or file error."); }
